config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  
  resources :users, only: [:edit, :show, :destroy, :index, :update] do
    member do
      get :following, :followers
    end
  end
  resources :articles do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :followed_id, presence: true
  validates :follower_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship',
            foreign_key: 'follower_id', dependent: :destroy 
  has_many :pasive_relationships, class_name: 'Relationship',
            foreign_key: 'followed_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :pasive_relationships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def following?(other_user)
    following.include?(other_user)
  end
  
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @user = User.find(@article.user_id)
  end

  def new
    @article = Article.new
  end

  def create
    @user = current_user
    @article = @user.articles.create(article_params)
    puts @article.title

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end

  def following
    @title = 'Follows'
    @user  = User.find(params[:id])
    @users = @user.following
    render 'users/show_follow'
  end

  def followers
    @title = 'Followers'
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'users/show_follow'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
   <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
   <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_session.html.erb
<% if current_user%>
  <%= link_to 'Log out', destroy_user_session_path, 'data-turbo-method': :delete%>
<% else%>
  <%= link_to 'Sing in', new_user_session_path %>
  <br />
  <%= link_to 'Sing up', new_user_registration_path %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<% if current_user.id == @article.id%>
  <%= render "form", article: @article %>
<% elsif current_user %>
  <p> You need to be logged to edit an article pls sing in with your account </p>
  <%= link_to "Sing in", new_user_session_path %>
<% else%>
  <p> You need to be the article author to edit it </p>
  <%= link_to 'Sing out', destroy_user_session_path, 'data-turbo-method': :delete%>
<% end %>

app/views/articles/index.html.erb
<h1 class = 'header'>Articles</h1>

<p class = 'title'>Our blog has <%= Article.public_count %> articles and counting!</p>

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to 'New Article', new_article_path %>
<br />

<%= link_to 'Show all users', users_path%>
<br />

<%= render 'session'%>

app/views/articles/new.html.erb
<h1>New Article</h1>

<% if current_user%>
  <%= render "form", article: @article %>
<% else%>
  <p> You need to be logged to create a new article pls sign in with your acount or sing up down below</p>
  <%= link_to "Sing in", new_user_session_path %>
  <br />
  <%= link_to "Sing up", new_user_registration_path %>
<% end %>
  

app/views/articles/show.html.erb
<h1 class = 'header'> Articles title: <%= @article.title %> <br/>Author: <%= link_to @user.name, @user %></h1>

<p class = 'body'><%= @article.body %></p>


<% if current_user.present? && (current_user.id == @article.user.id) %>
  <ul>
  <li><%= link_to 'Edit', edit_article_path(@article) %></li>
  <td><%= button_to 'Delete', article_path(@article), method: :delete, data: {confirm: 'Are you sure?'} %></td>
  </ul>
<% end %>

<div class = 'comments'>
<h2 class = 'title'>Comments</h2>
<%= render @article.comments %>


<% if current_user.present? && current_user.following?(@user)%>
  <h2 class = 'comment-box'>Add a comment:</h2>
  <%= render 'comments/form' %>
<% else %>
  <p> You can't comment remind that you need to be logged and follow the author to comment </p>
<% end %>
</div>  
<br/>
<%= render 'session'%>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <td><%= button_to 'Delete', article_comment_path(comment.article,comment), method: :delete, data: {confirm: "Are you sure?"} %></td>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |form| %>
  <div>
    <%= hidden_field_tag :followed_id, @user.id %>
  </div>
    <%= form.submit 'Follow', class: 'btn btn-success' %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user.present? && current_user.id != @user.id %>
  <div id = 'follow_form'>
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_show_users.html.erb
<ul>
  <% @users.each do |user| %>
      <li>
        <%= link_to user.name, user %>
      </li>
    <% end %>
</ul>

app/views/users/_stats.html.erb
<% @user ||= current_user%>
<div class = 'stats'>
  <a href = "<%= following_user_path(@user) %>">
    <strong id = 'following' class = 'stat'>
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href = "<%= followers_user_path(@user) %>">
    <strong id = 'followers'>
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit 'Unfollow', class: 'btn btn-outline-danger' %>
<% end %>

app/views/users/index.html.erb
<h1>This is the list of the registred users from the blog</h1>

<%= render 'show_users'%>

<%= render 'articles/session'%>

app/views/users/show.html.erb
<h2>This is the <%= @user.name %>'s page</h2>
<%= render 'stats'%>
<%= render 'follow_form'%>

app/views/users/show_follow.html.erb
<h1 class = 'header'> Those are <%= @user.name%>'s  <%= @title%></h1>
<%= render 'show_users'%>